# Automatic Ticket Classification using Many-to-One
RNN and Replied Back to Customer using LLM

In [5]:
# pip install -U datasets fsspec

In [ ]:
# pip install tensorflow==2.15.0

In [ ]:
# pip install keras==2.15.0

In [3]:
# pip install tf-keras

In [6]:
# pip install transformers==4.41.2

In [ ]:
# pip install huggingface-hub==0.23.5

In [ ]:
# pip install -q google-generativeai

In [ ]:
# import keras
# import tensorflow as tf
# import transformers

# print("keras:", keras.__version__)        # 2.15.0
# print("tf:", tf.__version__)              # 2.15.0
# print("transformers:", transformers.__version__)      # 4.41.2

In [47]:
from datasets import load_dataset

ds = load_dataset("Tobi-Bueck/customer-support-tickets")

In [48]:
print(ds)

DatasetDict({
    train: Dataset({
        features: ['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language', 'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7', 'tag_8'],
        num_rows: 61765
    })
})

In [49]:
train_ds = load_dataset(
    "Tobi-Bueck/customer-support-tickets",
    split="train"
)

print(train_ds)

Dataset({
    features: ['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language', 'version', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7', 'tag_8'],
    num_rows: 61765
})

In [50]:
import numpy as np
import pandas as pd

df = train_ds.to_pandas()

df.head(3)

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51.0,Security,Outage,Disruption,Data Breach,None,None,None,None
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51.0,Account,Disruption,Outage,IT,Tech Support,None,None,None
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51.0,Product,Feature,Tech Support,None,None,None,None,None

In [51]:
df = df[['body', 'queue']]

In [52]:
df.head()

                                                body                  queue
0  Sehr geehrtes Support-Team,\n\nich möchte eine...      Technical Support
1  Dear Customer Support Team,\n\nI am writing to...      Technical Support
2  Dear Customer Support Team,\n\nI hope this mes...  Returns and Exchanges
3  Dear Customer Support Team,\n\nI hope this mes...   Billing and Payments
4  Dear Support Team,\n\nI hope this message reac...    Sales and Pre-Sales

In [53]:
for i in range(5):
  print(df['body'][i])

Sehr geehrtes Support-Team,\n\nich möchte einen gravierenden Sicherheitsvorfall melden, der gegenwärtig mehrere Komponenten unserer Infrastruktur betrifft. Betroffene Geräte umfassen Projektoren, Bildschirme und Speicherlösungen auf Cloud-Plattformen. Der Grund für die Annahme ist, dass der Vorfall eine potenzielle Datenverletzung im Zusammenhang mit einer Cyberattacke darstellt, was ein erhebliches Risiko für sensible Informationen und den laufenden Geschäftsbetrieb unserer Organisation bedeutet.\n\nUnsere initialen Untersuchungen haben ungewöhnliche Aktivitäten und Abweichungen bei den Geräten ergeben. Trotz der Umsetzung unserer standardisierten Behebungs- und Eindämmungsmaßnahmen konnte die Bedrohung bislang nicht vollständig eliminiert.
Dear Customer Support Team,\n\nI am writing to report a significant problem with the centralized account management portal, which currently appears to be offline. This outage is blocking access to account settings, leading to substantial inconvenience. I have attempted to log in multiple times using different browsers and devices, but the issue persists.\n\nCould you please provide an update on the outage status and an estimated time for resolution? Also, are there any alternative ways to access and manage my account during this downtime?
Dear Customer Support Team,\n\nI hope this message reaches you well. I am reaching out to request detailed information about the capabilities of your smart home integration products listed on your website. As a potential customer aiming to develop a seamlessly interconnected home environment, it is essential to understand how your products interact with various smart home platforms.\n\nCould you kindly provide detailed compatibility information with popular smart home ecosystems such as Amazon Alexa, Google Assistant, and Apple?
Dear Customer Support Team,\n\nI hope this message finds you well. I am reaching out to request clarification about the billing and payment procedures linked to my account. Recently, I observed some inconsistencies in the charges applied and would like to ensure I fully understand the billing cycle, accepted payment options, and any potential extra charges.\n\nFirstly, I would be grateful if you could provide a detailed explanation of how the billing cycle functions. Specifically, I am interested in knowing the start and end dates.\n\nThank you for your assistance regarding these billing inquiries.
Dear Support Team,\n\nI hope this message reaches you well. I am reaching out to ask about the compatibility of your products with the specific needs of marketing agencies. Our company is considering adopting these solutions to streamline our current marketing processes and wants to confirm that the products are fully compatible with the tools and platforms we currently utilize.\n\nCould you please supply detailed information regarding the compatibility of your products with popular marketing software, CRM systems, email marketing applications, and analytics platforms? Additionally, I would appreciate any relevant case studies or documentation tailored to our use case.

In [54]:
# y.value_counts()

df['queue'].nunique()

52

# Preprocessing

## handling missing values

In [55]:
df.isnull().sum()

body     2
queue    0
dtype: int64

In [56]:
df[df['body'].isnull()]

       body            queue
59452  None  Product Support
59724  None  Product Support

In [57]:
df.dropna(inplace=True)

In [58]:
df.isnull().sum()

body     0
queue    0
dtype: int64

## clean the text

In [59]:
import re

def clean_text(text):
  text = text.lower()
  text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
  return text

df['clean_body'] = df['body'].apply(clean_text)

In [60]:
for i in range(5):
  print(df['clean_body'][i])

sehr geehrtes supportteamnnich mchte einen gravierenden sicherheitsvorfall melden der gegenwrtig mehrere komponenten unserer infrastruktur betrifft betroffene gerte umfassen projektoren bildschirme und speicherlsungen auf cloudplattformen der grund fr die annahme ist dass der vorfall eine potenzielle datenverletzung im zusammenhang mit einer cyberattacke darstellt was ein erhebliches risiko fr sensible informationen und den laufenden geschftsbetrieb unserer organisation bedeutetnnunsere initialen untersuchungen haben ungewhnliche aktivitten und abweichungen bei den gerten ergeben trotz der umsetzung unserer standardisierten behebungs und eindmmungsmanahmen konnte die bedrohung bislang nicht vollstndig eliminiert
dear customer support teamnni am writing to report a significant problem with the centralized account management portal which currently appears to be offline this outage is blocking access to account settings leading to substantial inconvenience i have attempted to log in multiple times using different browsers and devices but the issue persistsnncould you please provide an update on the outage status and an estimated time for resolution also are there any alternative ways to access and manage my account during this downtime
dear customer support teamnni hope this message reaches you well i am reaching out to request detailed information about the capabilities of your smart home integration products listed on your website as a potential customer aiming to develop a seamlessly interconnected home environment it is essential to understand how your products interact with various smart home platformsnncould you kindly provide detailed compatibility information with popular smart home ecosystems such as amazon alexa google assistant and apple
dear customer support teamnni hope this message finds you well i am reaching out to request clarification about the billing and payment procedures linked to my account recently i observed some inconsistencies in the charges applied and would like to ensure i fully understand the billing cycle accepted payment options and any potential extra chargesnnfirstly i would be grateful if you could provide a detailed explanation of how the billing cycle functions specifically i am interested in knowing the start and end datesnnthank you for your assistance regarding these billing inquiries
dear support teamnni hope this message reaches you well i am reaching out to ask about the compatibility of your products with the specific needs of marketing agencies our company is considering adopting these solutions to streamline our current marketing processes and wants to confirm that the products are fully compatible with the tools and platforms we currently utilizenncould you please supply detailed information regarding the compatibility of your products with popular marketing software crm systems email marketing applications and analytics platforms additionally i would appreciate any relevant case studies or documentation tailored to our use case

## Label Encoding

In [61]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['queue_encoded'] = le.fit_transform(df['queue'])

In [62]:
import pickle

with open("file/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

In [63]:
df.head(3)

,body,queue,clean_body,queue_encoded
0,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Technical Support,sehr geehrtes supportteamnnich mchte einen gra...,49
1,"Dear Customer Support Team,\n\nI am writing to...",Technical Support,dear customer support teamnni am writing to re...,49
2,"Dear Customer Support Team,\n\nI hope this mes...",Returns and Exchanges,dear customer support teamnni hope this messag...,41

## Train Test Split

In [64]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['clean_body'], df['queue_encoded'], test_size=0.2, random_state=42)

In [65]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((49410,), (12353,), (49410,), (12353,))

## Tokenization

In [66]:
from tensorflow.keras.preprocessing.text import Tokenizer       # tokenizer -> convert word into number (label encoder)

tokenizer = Tokenizer(num_words=10000)

tokenizer.fit_on_texts(X_train)

In [67]:
X_train_seq = tokenizer.texts_to_sequences(X_train)

X_test_seq = tokenizer.texts_to_sequences(X_test)

In [68]:
import pickle

with open("file/tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

## Padding

In [69]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train_pad = pad_sequences(X_train_seq, maxlen=100, padding='post')

X_test_pad = pad_sequences(X_test_seq, maxlen=100, padding='post')

# Model

## RNN

In [23]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [24]:
model = Sequential()

WARNING:tensorflow:From c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [25]:
# embedding layer

model.add(Embedding(
    input_dim = 10000,
    output_dim = 128,
    input_length = 100,
    trainable=True
))

In [26]:
# RNN layer

model.add(SimpleRNN(
    64,
    return_sequences=False  # True -> Many to Many, False -> Many to One
))

In [27]:
# Dense layer (output layer)

num_classes = df['queue'].nunique()   # 52

model.add(Dense(num_classes, activation='softmax'))

In [28]:
# compile

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

WARNING:tensorflow:From c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [29]:
# fit the model

history = model.fit(
    X_train_pad,
    y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/5
WARNING:tensorflow:From c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

1236/1236 [==============================] - 107s 82ms/step - loss: 2.8834 - accuracy: 0.2246 - val_loss: 2.8474 - val_accuracy: 0.2291
Epoch 2/5
1236/1236 [==============================] - 95s 76ms/step - loss: 2.8319 - accuracy: 0.2231 - val_loss: 2.7564 - val_accuracy: 0.2296
Epoch 3/5
1236/1236 [==============================] - 107s 87ms/step - loss: 2.8436 - accuracy: 0.2195 - val_loss: 3.3482 - val_accuracy: 0.1735
Epoch 4/5
1236/1236 [==============================] - 87s 70ms/step - loss: 2.5799 - accuracy: 0.2278 - val_loss: 2.4122 - val_accuracy: 0.2338
Epoch 5/5
1236/1236 [==============================] - 107s 87ms/step - loss: 2.4152 - accuracy: 0.2324 - val_loss: 2.4257 - val_accuracy: 0.2335

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 100, 128)          1280000

 simple_rnn (SimpleRNN)      (None, 64)                12352

 dense (Dense)               (None, 52)                3380

=================================================================
Total params: 1295732 (4.94 MB)
Trainable params: 1295732 (4.94 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [31]:
loss, accuracy = model.evaluate(X_test_pad, y_test)

print("Accuracy:", accuracy)

 29/387 [=>............................] - ETA: 7s - loss: 2.3893 - accuracy: 0.2586
Caching the list of root modules, please wait!
(This will only be done once - type '%rehashx' to reset cache!)

 48/387 [==>...........................] - ETA: 7s - loss: 2.4166 - accuracy: 0.2435

C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\IPython\core\completerlib.py:150: UserWarning: This is now an optional IPython functionality, setting rootmodules_cache requires you to install the `pickleshare` library.
  ip.db['rootmodules_cache'] = rootmodules_cache

387/387 [==============================] - 9s 23ms/step - loss: 2.4403 - accuracy: 0.2355
Accuracy: 0.2354893535375595

In [32]:
# from sklearn.metrics import classification_report

# y_pred_probs = model.predict(X_test_pad)

# y_pred = np.argmax(y_pred_probs, axis=1)

# print(classification_report(y_test, y_pred))

In [37]:
model.save("file/rnn_model.h5")

## LSTM

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [43]:
model = Sequential()

In [44]:
# embedding layer

model.add(Embedding(
    input_dim = 10000,
    output_dim = 128,
    input_length = 100,
    trainable=True
))

In [45]:
# LSTM layer

model.add(LSTM(
    64,
    return_sequences=False
    ))

In [46]:
# Dense layer

model.add(Dense(32, activation='relu'))

In [47]:
# Dense layer (output layer)

num_classes = df['queue'].nunique()   # 52

model.add(Dense(num_classes, activation='softmax'))

In [48]:
# Compile

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [49]:
history = model.fit(
    X_train_pad,
    y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/5
1236/1236 [==============================] - 242s 191ms/step - loss: 2.7395 - accuracy: 0.2255 - val_loss: 2.5697 - val_accuracy: 0.2295
Epoch 2/5
1236/1236 [==============================] - 231s 187ms/step - loss: 2.4234 - accuracy: 0.2306 - val_loss: 2.3696 - val_accuracy: 0.2321
Epoch 3/5
1236/1236 [==============================] - 163s 132ms/step - loss: 2.3800 - accuracy: 0.2329 - val_loss: 2.3723 - val_accuracy: 0.2345
Epoch 4/5
1236/1236 [==============================] - 167s 135ms/step - loss: 2.4329 - accuracy: 0.2370 - val_loss: 2.3596 - val_accuracy: 0.2505
Epoch 5/5
1236/1236 [==============================] - 170s 137ms/step - loss: 2.2872 - accuracy: 0.2733 - val_loss: 2.2565 - val_accuracy: 0.2806

In [50]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_2 (Embedding)     (None, 100, 128)          1280000

 lstm_1 (LSTM)               (None, 64)                49408

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 52)                1716

=================================================================
Total params: 1333204 (5.09 MB)
Trainable params: 1333204 (5.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [51]:
loss, accuracy = model.evaluate(X_test_pad, y_test)

print("Accuracy:", accuracy)

387/387 [==============================] - 14s 36ms/step - loss: 2.2633 - accuracy: 0.2830
Accuracy: 0.2830081880092621

In [52]:
# from sklearn.metrics import classification_report

# y_pred_probs = model.predict(X_test_pad)

# y_pred = np.argmax(y_pred_probs, axis=1)

# print(classification_report(y_test, y_pred))

In [53]:
model.save("file/lstm_model.h5")

c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

## Bidirectional LSTM

In [70]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, Dense, Bidirectional, LSTM

In [71]:
model = Sequential()

In [72]:
# embedding layer

model.add(Embedding(
    input_dim = 10000,
    output_dim = 128,
    input_length = 100,
    trainable=True
))

In [73]:
# Bi-directional LSTM layer

model.add(Bidirectional(LSTM(
    64,
    return_sequences=False
    )))

In [74]:
# Dense layer

model.add(Dense(32, activation='relu'))

In [75]:
# Dense layer (output layer)

num_classes = df['queue'].nunique()   # 52

model.add(Dense(num_classes, activation='softmax'))

In [76]:
# Compile

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

WARNING:tensorflow:From c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [77]:
history = model.fit(
    X_train_pad,
    y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/5
WARNING:tensorflow:From c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

1236/1236 [==============================] - 154s 118ms/step - loss: 2.3334 - accuracy: 0.2639 - val_loss: 2.1500 - val_accuracy: 0.2978
Epoch 2/5
1236/1236 [==============================] - 151s 122ms/step - loss: 2.0637 - accuracy: 0.3315 - val_loss: 2.0114 - val_accuracy: 0.3438
Epoch 3/5
1236/1236 [==============================] - 169s 137ms/step - loss: 1.8364 - accuracy: 0.3916 - val_loss: 1.8688 - val_accuracy: 0.3818
Epoch 4/5
1236/1236 [==============================] - 177s 143ms/step - loss: 1.5952 - accuracy: 0.4701 - val_loss: 1.7627 - val_accuracy: 0.4248
Epoch 5/5
1236/1236 [==============================] - 163s 132ms/step - loss: 1.3379 - accuracy: 0.5592 - val_loss: 1.6792 - val_accuracy: 0.4674

In [78]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_1 (Embedding)     (None, 100, 128)          1280000

 bidirectional (Bidirection  (None, 128)               98816
 al)

 dense (Dense)               (None, 32)                4128

 dense_1 (Dense)             (None, 52)                1716

=================================================================
Total params: 1384660 (5.28 MB)
Trainable params: 1384660 (5.28 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [79]:
loss, accuracy = model.evaluate(X_test_pad, y_test)

print("Accuracy:", accuracy)

387/387 [==============================] - 12s 31ms/step - loss: 1.6937 - accuracy: 0.4718
Accuracy: 0.471788227558136

In [80]:
from sklearn.metrics import classification_report

y_pred_probs = model.predict(X_test_pad)

y_pred = np.argmax(y_pred_probs, axis=1)

print(classification_report(y_test, y_pred))

387/387 [==============================] - 15s 30ms/step
              precision    recall  f1-score   support

           0       0.69      0.20      0.31        54
           1       0.56      0.57      0.56        77
           2       0.31      0.06      0.11        62
           3       0.31      0.23      0.26        66
           4       0.58      0.78      0.67        55
           5       0.37      0.22      0.27        60
           6       0.82      0.69      0.75       972
           7       0.21      0.46      0.29        52
           8       0.73      0.59      0.65        63
           9       0.46      0.58      0.51        73
          10       0.35      0.49      0.40      1477
          11       0.62      0.62      0.62        66
          12       0.58      0.52      0.55        54
          13       0.44      0.11      0.18        71
          14       0.19      0.10      0.13        60
          15       0.55      0.49      0.52        67
          16       0.20      0.01      0.01       131
          17       0.34      0.58      0.42        83
          18       0.38      0.88      0.53        67
          19       0.47      0.58      0.52        64
          20       0.41      0.29      0.34        75
          21       0.44      0.42      0.43        66
          22       0.26      0.16      0.20        56
          23       0.56      0.13      0.21       194
          24       0.49      0.71      0.58        63
          25       0.80      0.74      0.77        50
          26       0.62      0.64      0.63        66
          27       0.85      0.66      0.74        59
          28       0.40      0.40      0.40      1083
          29       0.36      0.33      0.35        81
          30       0.48      0.62      0.54        55
          31       0.00      0.00      0.00        76
          32       0.30      0.32      0.31        53
          33       0.19      0.29      0.23        82
          34       0.83      0.86      0.84        76
          35       0.37      0.32      0.34        72
          36       0.22      0.38      0.27        45
          37       0.40      0.21      0.28        76
          38       0.34      0.61      0.44        80
          39       0.48      0.34      0.40      1767
          40       0.17      0.20      0.18        41
          41       0.40      0.22      0.28       536
          42       0.21      0.02      0.04       284
          43       0.40      0.30      0.35        56
          44       0.52      0.26      0.35        65
          45       0.61      0.54      0.58       371
          46       0.55      0.80      0.65        60
          47       0.70      0.59      0.64        54
          48       0.29      0.31      0.30        51
          49       0.51      0.66      0.57      2869
          50       0.75      0.46      0.57        52
          51       0.23      0.28      0.25        65

    accuracy                           0.47     12353
   macro avg       0.45      0.42      0.41     12353
weighted avg       0.47      0.47      0.46     12353

c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [81]:
model.save("file/bidir_lstm_model.keras")

### gemini

In [32]:
# load the model
from tensorflow.keras.models import load_model

model = load_model("file/bidir_lstm_model.h5")

WARNING:tensorflow:From c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [33]:
# Test with new ticket

sample_ticket = """
I am unable to access my account and the login page keeps crashing.
"""

In [34]:
# preprocess

sample_clean = clean_text(sample_ticket)

sample_seq = tokenizer.texts_to_sequences([sample_clean])   # tokenizer

sample_pad = pad_sequences(sample_seq, maxlen=100)      # padding

In [35]:
# Predict

prediction = model.predict(sample_pad)

predicted_class = np.argmax(prediction)

predicted_queue = le.inverse_transform([predicted_class])

print("Predicted Queue:", predicted_queue[0])

1/1 [==============================] - 2s 2s/step
Predicted Queue: Product Support

In [36]:
import google.generativeai as genai

genai.configure(api_key="AIzaSyBaO_jDOoqpmZT6C_tqoL2AHeaRwL_cfm0")

In [37]:
model_gemini = genai.GenerativeModel("gemini-2.5-flash")

In [38]:
prompt = f"""
Customer Ticket:
{sample_ticket}

Predicted Department:
{predicted_queue[0]}

Generate a polite customer support reply acknowledging the issue.
"""

In [39]:
response = model_gemini.generate_content(prompt)

print(response.text)

Hello,

Thank you for reaching out to us. I'm sorry to hear that you're experiencing difficulties accessing your account and that the login page keeps crashing. I understand how frustrating this can be.

We've received your ticket, and the issue you've described falls squarely within the expertise of our Product Support team. They are the best people to investigate why the login page is crashing and help you regain access to your account.

We've forwarded your ticket directly to them, and they will review your issue and get back to you with further assistance as soon as possible.

Thank you for your patience while we work to resolve this for you.

Best regards,
The Customer Support Team

## GRU (Gated Recurrent Unit)

In [66]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, Dense, GRU

In [67]:
model = Sequential()

In [68]:
# embedding layer

model.add(Embedding(
    input_dim = 10000,
    output_dim = 128,
    input_length = 100,
    trainable=True
))

In [69]:
# GRU layer

model.add(GRU(64))

In [70]:
# Dense

model.add(Dense(32, activation='relu'))

In [71]:
# Dense layer (output layer)

num_classes = df['queue'].nunique()   # 52

model.add(Dense(num_classes, activation='softmax'))

In [72]:
# Compile

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [73]:
history = model.fit(
    X_train_pad,
    y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/5
1236/1236 [==============================] - 120s 93ms/step - loss: 2.4732 - accuracy: 0.2423 - val_loss: 2.2549 - val_accuracy: 0.2811
Epoch 2/5
1236/1236 [==============================] - 103s 83ms/step - loss: 2.1670 - accuracy: 0.3052 - val_loss: 2.1279 - val_accuracy: 0.3158
Epoch 3/5
1236/1236 [==============================] - 109s 88ms/step - loss: 2.0275 - accuracy: 0.3535 - val_loss: 2.0735 - val_accuracy: 0.3390
Epoch 4/5
1236/1236 [==============================] - 113s 91ms/step - loss: 1.8515 - accuracy: 0.4086 - val_loss: 1.9569 - val_accuracy: 0.3718
Epoch 5/5
1236/1236 [==============================] - 114s 92ms/step - loss: 1.6019 - accuracy: 0.4787 - val_loss: 1.8257 - val_accuracy: 0.4264

In [74]:
loss, accuracy = model.evaluate(X_test_pad, y_test)

print("Accuracy:", accuracy)

387/387 [==============================] - 12s 32ms/step - loss: 1.8295 - accuracy: 0.4298
Accuracy: 0.42977413535118103

In [75]:
# from sklearn.metrics import classification_report

# y_pred_probs = model.predict(X_test_pad)

# y_pred = np.argmax(y_pred_probs, axis=1)

# print(classification_report(y_test, y_pred))

In [76]:
model.save("file/gru_model.h5")

## Transformers

### BERT (Bidirectional Encoder Representations from Transformers)

#### Tokenization

In [28]:
import tensorflow as tf

In [29]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [30]:
train_encodings = tokenizer(
    list(X_train),
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='tf'
)

In [31]:
test_encodings = tokenizer(
    list(X_test),
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='tf'
)

In [32]:
y_train = tf.convert_to_tensor(y_train)
y_test = tf.convert_to_tensor(y_test)

In [33]:
train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(train_encodings),
    y_train
))

test_dataset = tf.data.Dataset.from_tensor_slices((
    dict(test_encodings),
    y_test
))

In [34]:
batch_size = 16

train_dataset = train_dataset.shuffle(1000).batch(batch_size)

test_dataset = test_dataset.batch(batch_size)

In [1]:
from transformers import TFBertForSequenceClassification

num_classes = df['queue'].nunique()

model = TFBertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=num_classes
)

c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

WARNING:tensorflow:From c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

NameError: name 'df' is not defined

In [ ]:
from transformers import create_optimizer

optimizer, schedule = create_optimizer(
    init_lr=2e-5,
    num_train_steps=len(train_dataset) * 3,
    num_warmup_steps=0
)

loss = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True
)

model.compile(
    optimizer=optimizer,
    loss=loss,
    metrics=['accuracy']
)

In [ ]:
history = model.fit(
    train_dataset,
    validation_data=test_dataset,
    epochs=3
)

Epoch 1/3

WARNING:tensorflow:AutoGraph could not transform <function infer_framework at 0x7a9f5c7174c0> and will run it as-is.
Cause: for/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

WARNING: AutoGraph could not transform <function infer_framework at 0x7a9f5c7174c0> and will run it as-is.
Cause: for/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
  52/3089 [..............................] - ETA: 18:53:54 - loss: 3.4363 - accuracy: 0.1863

In [ ]:
loss, accuracy = model.evaluate(test_dataset)

print("Test Accuracy:", accuracy)

In [ ]:
predictions = model.predict(test_dataset)

In [ ]:
y_pred = np.argmax(
    predictions.logits,
    axis=1
)

In [ ]:
print(classification_report(
    y_test,
    y_pred
))